"""
Complete S&P 500 and Nasdaq-100 universe.

S&P 500: 503 constituents as of July 2026 (source: datasets/s-and-p-500-companies on GitHub)
Nasdaq-100: 100 constituents as of July 2026

This file is the single source of truth for the investment universe.
Updated by universe_sync.py weekly from Wikipedia (runtime) or manually here (static fallback).
The live sync compares this list against the DB and adds/removes constituents.
"""

# ── S&P 500 — 503 tickers (includes dual-class shares for GOOGL/GOOG, FOX/FOXA, NWS/NWSA) ──
SP500_TICKERS = [
    # Communication Services (23)
    "CHTR", "CMCSA", "DIS", "EA", "ECHO", "FOX", "FOXA", "GOOG", "GOOGL", "LYV",
    "META", "NFLX", "NWS", "NWSA", "OMC", "PSKY", "T", "TKO", "TMUS", "TTD",
    "TTWO", "VZ", "WBD",

    # Consumer Discretionary (47)
    "ABNB", "AMZN", "APTV", "AZO", "BBY", "BKNG", "CCL", "CMG", "CVNA", "DASH",
    "DECK", "DHI", "DPZ", "DRI", "EBAY", "EXPE", "F", "GM", "GPC", "GRMN",
    "HAS", "HD", "HLT", "LEN", "LOW", "LULU", "LVS", "MAR", "MCD", "MGM",
    "NCLH", "NKE", "NVR", "ORLY", "PHM", "RCL", "RL", "ROST", "SBUX", "TJX",
    "TPR", "TSCO", "TSLA", "ULTA", "WSM", "WYNN", "YUM",

    # Consumer Staples (34)
    "ADM", "BF-B", "BG", "CASY", "CHD", "CL", "CLX", "COST", "DG", "DLTR",
    "EL", "GIS", "HRL", "HSY", "KDP", "KHC", "KMB", "KO", "KR", "KVUE",
    "MDLZ", "MKC", "MNST", "MO", "PEP", "PG", "PM", "SJM", "STZ", "SYY",
    "TAP", "TGT", "TSN", "WMT",

    # Energy (21)
    "APA", "BKR", "COP", "CVX", "DVN", "EOG", "EQT", "EXE", "FANG", "HAL",
    "KMI", "MPC", "OKE", "OXY", "PSX", "SLB", "TPL", "TRGP", "VLO", "WMB",
    "XOM",

    # Financials (76)
    "ACGL", "AFL", "AIG", "AIZ", "AJG", "ALL", "AMP", "AON", "APO", "ARES",
    "AXP", "BAC", "BEN", "BLK", "BNY", "BRK-B", "BRO", "BX", "C", "CB",
    "CBOE", "CFG", "CINF", "CME", "COF", "COIN", "CPAY", "EG", "ERIE", "FDS",
    "FIS", "FISV", "FITB", "GL", "GPN", "GS", "HBAN", "HIG", "HOOD", "IBKR",
    "ICE", "IVZ", "JKHY", "JPM", "KEY", "KKR", "L", "MA", "MCO", "MET",
    "MRSH", "MS", "MSCI", "MTB", "NDAQ", "NTRS", "PFG", "PGR", "PNC", "PRU",
    "PYPL", "RF", "RJF", "SCHW", "SPGI", "STT", "SYF", "TFC", "TROW", "TRV",
    "USB", "V", "WFC", "WRB", "WTW", "XYZ",

    # Health Care (59)
    "A", "ABBV", "ABT", "ALGN", "AMGN", "BAX", "BDX", "BIIB", "BMY", "BSX",
    "CAH", "CI", "CNC", "COO", "COR", "CRL", "CVS", "DGX", "DHR", "DVA",
    "DXCM", "ELV", "EW", "GEHC", "GILD", "HCA", "HSIC", "HUM", "IDXX", "INCY",
    "IQV", "ISRG", "JNJ", "LH", "LLY", "MCK", "MDT", "MRK", "MRNA", "MTD",
    "PFE", "PODD", "REGN", "RMD", "RVTY", "SOLV", "STE", "SYK", "TECH", "TMO",
    "UHS", "UNH", "VEEV", "VRTX", "VTRS", "WAT", "WST", "ZBH", "ZTS",

    # Industrials (81)
    "ADP", "ALLE", "AME", "AOS", "AXON", "BA", "BLDR", "BR", "CARR", "CAT",
    "CHRW", "CMI", "CPRT", "CSX", "CTAS", "DAL", "DE", "DOV", "EFX", "EME",
    "EMR", "ETN", "EXPD", "FAST", "FDX", "FDXF", "FIX", "FTV", "GD", "GE",
    "GEV", "GNRC", "GWW", "HII", "HON", "HONA", "HUBB", "HWM", "IEX", "IR",
    "ITW", "J", "JBHT", "JCI", "LDOS", "LHX", "LII", "LMT", "LUV", "MAS",
    "MMM", "NDSN", "NOC", "NSC", "ODFL", "OTIS", "PAYX", "PCAR", "PH", "PNR",
    "PWR", "ROK", "ROL", "RSG", "RTX", "SNA", "SWK", "TDG", "TT", "TXT",
    "UAL", "UBER", "UNP", "UPS", "URI", "VLTO", "VRSK", "VRT", "WAB", "WM",
    "XYL",

    # Information Technology (74)
    "AAPL", "ACN", "ADBE", "ADI", "ADSK", "AKAM", "AMAT", "AMD", "ANET", "APH",
    "APP", "AVGO", "CDNS", "CDW", "CIEN", "COHR", "CRM", "CRWD", "CSCO", "CTSH",
    "DDOG", "DELL", "FFIV", "FICO", "FLEX", "FSLR", "FTNT", "GDDY", "GEN", "GLW",
    "HPE", "HPQ", "IBM", "INTC", "INTU", "IT", "JBL", "KEYS", "KLAC", "LITE",
    "LRCX", "MCHP", "MPWR", "MRVL", "MSFT", "MSI", "MU", "NOW", "NTAP", "NVDA",
    "NXPI", "ON", "ORCL", "PANW", "PLTR", "PTC", "Q", "QCOM", "ROP", "SMCI",
    "SNDK", "SNPS", "STX", "SWKS", "TDY", "TEL", "TER", "TRMB", "TXN", "TYL",
    "VRSN", "WDAY", "WDC", "ZBRA",

    # Materials (26)
    "ALB", "AMCR", "APD", "AVY", "BALL", "CF", "CRH", "CTVA", "DD", "DOW",
    "ECL", "FCX", "IFF", "IP", "LIN", "LYB", "MLM", "MOS", "NEM", "NUE",
    "PKG", "PPG", "SHW", "STLD", "SW", "VMC",

    # Real Estate (31)
    "AMT", "ARE", "AVB", "BXP", "CBRE", "CCI", "CPT", "CSGP", "DLR", "DOC",
    "EQIX", "EQR", "ESS", "EXR", "FRT", "HST", "INVH", "IRM", "KIM", "MAA",
    "O", "PLD", "PSA", "REG", "SBAC", "SPG", "UDR", "VICI", "VTR", "WELL",
    "WY",

    # Utilities (31)
    "AEE", "AEP", "AES", "ATO", "AWK", "CEG", "CMS", "CNP", "D", "DTE",
    "DUK", "ED", "EIX", "ES", "ETR", "EVRG", "EXC", "FE", "LNT", "NEE",
    "NI", "NRG", "PCG", "PEG", "PNW", "PPL", "SO", "SRE", "VST", "WEC",
    "XEL",

]

# ── Nasdaq-100 — current constituents ──────────────────────────────────────
NASDAQ100_TICKERS = [
    "AAPL", "ABNB", "ADBE", "ADI", "ADP", "AEP", "ALGN", "AMAT", "AMD", "AMGN",
    "AMZN", "ANSS", "APP", "ASML", "AVGO", "AXON", "BIIB", "BKNG", "CDNS", "CEG",
    "COST", "CPRT", "CRWD", "CSCO", "CSX", "CTAS", "CTSH", "DASH", "DDOG", "DECK",
    "DLTR", "DXCM", "EA", "EBAY", "ENPH", "EXC", "FANG", "FAST", "FTNT", "GEHC",
    "GFS", "GILD", "GOOG", "GOOGL", "HON", "IDXX", "INTC", "INTU", "ISRG", "KDP",
    "KLAC", "LIN", "LRCX", "LULU", "MCHP", "MDLZ", "MELI", "META", "MNST", "MRNA",
    "MRVL", "MSFT", "MU", "NFLX", "NVDA", "NXPI", "ODFL", "ON", "ORLY", "PANW",
    "PAYX", "PCAR", "PEP", "PYPL", "QCOM", "REGN", "RIVN", "ROP", "ROST", "SBUX",
    "SNPS", "TEAM", "TMUS", "TSLA", "TTD", "TTWO", "TXN", "VRSK", "VRTX", "WBA",
    "WBD", "WDAY", "XEL", "ZS",
]

# ── GICS sector/industry metadata for S&P 500 constituents ─────────────────
# Source: datasets/s-and-p-500-companies GitHub repository
# Keyed by ticker; used to populate company metadata on seed and universe sync
SP500_METADATA = {
    "A": {"name": "Agilent Technologies", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0001090872"},
    "AAPL": {"name": "Apple Inc.", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0000320193"},
    "ABBV": {"name": "AbbVie", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0001551152"},
    "ABNB": {"name": "Airbnb", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001559720"},
    "ABT": {"name": "Abbott Laboratories", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000001800"},
    "ACGL": {"name": "Arch Capital Group", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000947484"},
    "ACN": {"name": "Accenture", "sector": "Information Technology", "sub_industry": "IT Consulting & Other Services", "cik": "0001467373"},
    "ADBE": {"name": "Adobe Inc.", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000796343"},
    "ADI": {"name": "Analog Devices", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000006281"},
    "ADM": {"name": "Archer Daniels Midland", "sector": "Consumer Staples", "sub_industry": "Agricultural Products & Services", "cik": "0000007084"},
    "ADP": {"name": "Automatic Data Processing", "sector": "Industrials", "sub_industry": "Human Resource & Employment Services", "cik": "0000008670"},
    "ADSK": {"name": "Autodesk", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000769397"},
    "AEE": {"name": "Ameren", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001002910"},
    "AEP": {"name": "American Electric Power", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000004904"},
    "AES": {"name": "AES Corporation", "sector": "Utilities", "sub_industry": "Independent Power Producers & Energy Traders", "cik": "0000874761"},
    "AFL": {"name": "Aflac", "sector": "Financials", "sub_industry": "Life & Health Insurance", "cik": "0000004977"},
    "AIG": {"name": "American International Group", "sector": "Financials", "sub_industry": "Multi-line Insurance", "cik": "0000005272"},
    "AIZ": {"name": "Assurant", "sector": "Financials", "sub_industry": "Multi-line Insurance", "cik": "0001267238"},
    "AJG": {"name": "Arthur J. Gallagher & Co.", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0000354190"},
    "AKAM": {"name": "Akamai Technologies", "sector": "Information Technology", "sub_industry": "Internet Services & Infrastructure", "cik": "0001086222"},
    "ALB": {"name": "Albemarle Corporation", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0000915913"},
    "ALGN": {"name": "Align Technology", "sector": "Health Care", "sub_industry": "Health Care Supplies", "cik": "0001097149"},
    "ALL": {"name": "Allstate", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000899051"},
    "ALLE": {"name": "Allegion", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0001579241"},
    "AMAT": {"name": "Applied Materials", "sector": "Information Technology", "sub_industry": "Semiconductor Materials & Equipment", "cik": "0000006951"},
    "AMCR": {"name": "Amcor", "sector": "Materials", "sub_industry": "Paper & Plastic Packaging Products & Materials", "cik": "0001748790"},
    "AMD": {"name": "Advanced Micro Devices", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000002488"},
    "AME": {"name": "Ametek", "sector": "Industrials", "sub_industry": "Electrical Components & Equipment", "cik": "0001037868"},
    "AMGN": {"name": "Amgen", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000318154"},
    "AMP": {"name": "Ameriprise Financial", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0000820027"},
    "AMT": {"name": "American Tower", "sector": "Real Estate", "sub_industry": "Telecom Tower REITs", "cik": "0001053507"},
    "AMZN": {"name": "Amazon", "sector": "Consumer Discretionary", "sub_industry": "Broadline Retail", "cik": "0001018724"},
    "ANET": {"name": "Arista Networks", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0001596532"},
    "AON": {"name": "Aon plc", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0000315293"},
    "AOS": {"name": "A. O. Smith", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0000091142"},
    "APA": {"name": "APA Corporation", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0001841666"},
    "APD": {"name": "Air Products", "sector": "Materials", "sub_industry": "Industrial Gases", "cik": "0000002969"},
    "APH": {"name": "Amphenol", "sector": "Information Technology", "sub_industry": "Electronic Components", "cik": "0000820313"},
    "APO": {"name": "Apollo Global Management", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001858681"},
    "APP": {"name": "AppLovin", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001751008"},
    "APTV": {"name": "Aptiv", "sector": "Consumer Discretionary", "sub_industry": "Automotive Parts & Equipment", "cik": "0001521332"},
    "ARE": {"name": "Alexandria Real Estate Equities", "sector": "Real Estate", "sub_industry": "Office REITs", "cik": "0001035443"},
    "ARES": {"name": "Ares Management", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001176948"},
    "ATO": {"name": "Atmos Energy", "sector": "Utilities", "sub_industry": "Gas Utilities", "cik": "0000731802"},
    "AVB": {"name": "AvalonBay Communities", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000915912"},
    "AVGO": {"name": "Broadcom", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001730168"},
    "AVY": {"name": "Avery Dennison", "sector": "Materials", "sub_industry": "Paper & Plastic Packaging Products & Materials", "cik": "0000008818"},
    "AWK": {"name": "American Water Works", "sector": "Utilities", "sub_industry": "Water Utilities", "cik": "0001410636"},
    "AXON": {"name": "Axon Enterprise", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0001069183"},
    "AXP": {"name": "American Express", "sector": "Financials", "sub_industry": "Consumer Finance", "cik": "0000004962"},
    "AZO": {"name": "AutoZone", "sector": "Consumer Discretionary", "sub_industry": "Automotive Retail", "cik": "0000866787"},
    "BA": {"name": "Boeing", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000012927"},
    "BAC": {"name": "Bank of America", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000070858"},
    "BALL": {"name": "Ball Corporation", "sector": "Materials", "sub_industry": "Metal, Glass & Plastic Containers", "cik": "0000009389"},
    "BAX": {"name": "Baxter International", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000010456"},
    "BBY": {"name": "Best Buy", "sector": "Consumer Discretionary", "sub_industry": "Computer & Electronics Retail", "cik": "0000764478"},
    "BDX": {"name": "Becton Dickinson", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000010795"},
    "BEN": {"name": "Franklin Resources", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0000038777"},
    "BF-B": {"name": "Brown–Forman", "sector": "Consumer Staples", "sub_industry": "Distillers & Vintners", "cik": "0000014693"},
    "BG": {"name": "Bunge Global", "sector": "Consumer Staples", "sub_industry": "Agricultural Products & Services", "cik": "0001996862"},
    "BIIB": {"name": "Biogen", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000875045"},
    "BKNG": {"name": "Booking Holdings", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001075531"},
    "BKR": {"name": "Baker Hughes", "sector": "Energy", "sub_industry": "Oil & Gas Equipment & Services", "cik": "0001701605"},
    "BLDR": {"name": "Builders FirstSource", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0001316835"},
    "BLK": {"name": "BlackRock", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0002012383"},
    "BMY": {"name": "Bristol Myers Squibb", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0000014272"},
    "BNY": {"name": "BNY Mellon", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001390777"},
    "BR": {"name": "Broadridge Financial Solutions", "sector": "Industrials", "sub_industry": "Data Processing & Outsourced Services", "cik": "0001383312"},
    "BRK-B": {"name": "Berkshire Hathaway", "sector": "Financials", "sub_industry": "Multi-Sector Holdings", "cik": "0001067983"},
    "BRO": {"name": "Brown & Brown", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0000079282"},
    "BSX": {"name": "Boston Scientific", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000885725"},
    "BX": {"name": "Blackstone Inc.", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001393818"},
    "BXP": {"name": "BXP, Inc.", "sector": "Real Estate", "sub_industry": "Office REITs", "cik": "0001037540"},
    "C": {"name": "Citigroup", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000831001"},
    "CAH": {"name": "Cardinal Health", "sector": "Health Care", "sub_industry": "Health Care Distributors", "cik": "0000721371"},
    "CARR": {"name": "Carrier Global", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0001783180"},
    "CASY": {"name": "Casey\'s", "sector": "Consumer Staples", "sub_industry": "Food Retail", "cik": "0000726958"},
    "CAT": {"name": "Caterpillar Inc.", "sector": "Industrials", "sub_industry": "Construction Machinery & Heavy Transportation Equipment", "cik": "0000018230"},
    "CB": {"name": "Chubb Limited", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000896159"},
    "CBOE": {"name": "Cboe Global Markets", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001374310"},
    "CBRE": {"name": "CBRE Group", "sector": "Real Estate", "sub_industry": "Real Estate Services", "cik": "0001138118"},
    "CCI": {"name": "Crown Castle", "sector": "Real Estate", "sub_industry": "Telecom Tower REITs", "cik": "0001051470"},
    "CCL": {"name": "Carnival Corporation", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0000815097"},
    "CDNS": {"name": "Cadence Design Systems", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000813672"},
    "CDW": {"name": "CDW Corporation", "sector": "Information Technology", "sub_industry": "Technology Distributors", "cik": "0001402057"},
    "CEG": {"name": "Constellation Energy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001868275"},
    "CF": {"name": "CF Industries", "sector": "Materials", "sub_industry": "Fertilizers & Agricultural Chemicals", "cik": "0001324404"},
    "CFG": {"name": "Citizens Financial Group", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0000759944"},
    "CHD": {"name": "Church & Dwight", "sector": "Consumer Staples", "sub_industry": "Household Products", "cik": "0000313927"},
    "CHRW": {"name": "C.H. Robinson", "sector": "Industrials", "sub_industry": "Air Freight & Logistics", "cik": "0001043277"},
    "CHTR": {"name": "Charter Communications", "sector": "Communication Services", "sub_industry": "Cable & Satellite", "cik": "0001091667"},
    "CI": {"name": "Cigna", "sector": "Health Care", "sub_industry": "Health Care Services", "cik": "0001739940"},
    "CIEN": {"name": "Ciena", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0000936395"},
    "CINF": {"name": "Cincinnati Financial", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000020286"},
    "CL": {"name": "Colgate-Palmolive", "sector": "Consumer Staples", "sub_industry": "Household Products", "cik": "0000021665"},
    "CLX": {"name": "Clorox", "sector": "Consumer Staples", "sub_industry": "Household Products", "cik": "0000021076"},
    "CMCSA": {"name": "Comcast", "sector": "Communication Services", "sub_industry": "Cable & Satellite", "cik": "0001166691"},
    "CME": {"name": "CME Group", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001156375"},
    "CMG": {"name": "Chipotle Mexican Grill", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0001058090"},
    "CMI": {"name": "Cummins", "sector": "Industrials", "sub_industry": "Construction Machinery & Heavy Transportation Equipment", "cik": "0000026172"},
    "CMS": {"name": "CMS Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000811156"},
    "CNC": {"name": "Centene Corporation", "sector": "Health Care", "sub_industry": "Managed Health Care", "cik": "0001071739"},
    "CNP": {"name": "CenterPoint Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001130310"},
    "COF": {"name": "Capital One", "sector": "Financials", "sub_industry": "Consumer Finance", "cik": "0000927628"},
    "COHR": {"name": "Coherent Corp.", "sector": "Information Technology", "sub_industry": "Electronic Components", "cik": "0000820318"},
    "COIN": {"name": "Coinbase", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001679788"},
    "COO": {"name": "Cooper Companies (The)", "sector": "Health Care", "sub_industry": "Health Care Supplies", "cik": "0000711404"},
    "COP": {"name": "ConocoPhillips", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0001163165"},
    "COR": {"name": "Cencora", "sector": "Health Care", "sub_industry": "Health Care Distributors", "cik": "0001140859"},
    "COST": {"name": "Costco", "sector": "Consumer Staples", "sub_industry": "Consumer Staples Merchandise Retail", "cik": "0000909832"},
    "CPAY": {"name": "Corpay", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001175454"},
    "CPRT": {"name": "Copart", "sector": "Industrials", "sub_industry": "Diversified Support Services", "cik": "0000900075"},
    "CPT": {"name": "Camden Property Trust", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000906345"},
    "CRH": {"name": "CRH plc", "sector": "Materials", "sub_industry": "Construction Materials", "cik": "0000849395"},
    "CRL": {"name": "Charles River Laboratories", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0001100682"},
    "CRM": {"name": "Salesforce", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001108524"},
    "CRWD": {"name": "CrowdStrike", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0001535527"},
    "CSCO": {"name": "Cisco", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0000858877"},
    "CSGP": {"name": "CoStar Group", "sector": "Real Estate", "sub_industry": "Real Estate Services", "cik": "0001057352"},
    "CSX": {"name": "CSX Corporation", "sector": "Industrials", "sub_industry": "Rail Transportation", "cik": "0000277948"},
    "CTAS": {"name": "Cintas", "sector": "Industrials", "sub_industry": "Diversified Support Services", "cik": "0000723254"},
    "CTSH": {"name": "Cognizant", "sector": "Information Technology", "sub_industry": "IT Consulting & Other Services", "cik": "0001058290"},
    "CTVA": {"name": "Corteva", "sector": "Materials", "sub_industry": "Fertilizers & Agricultural Chemicals", "cik": "0001755672"},
    "CVNA": {"name": "Carvana", "sector": "Consumer Discretionary", "sub_industry": "Automotive Retail", "cik": "0001690820"},
    "CVS": {"name": "CVS Health", "sector": "Health Care", "sub_industry": "Health Care Services", "cik": "0000064803"},
    "CVX": {"name": "Chevron Corporation", "sector": "Energy", "sub_industry": "Integrated Oil & Gas", "cik": "0000093410"},
    "D": {"name": "Dominion Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000715957"},
    "DAL": {"name": "Delta Air Lines", "sector": "Industrials", "sub_industry": "Passenger Airlines", "cik": "0000027904"},
    "DASH": {"name": "DoorDash", "sector": "Consumer Discretionary", "sub_industry": "Specialized Consumer Services", "cik": "0001792789"},
    "DD": {"name": "DuPont", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0001666700"},
    "DDOG": {"name": "Datadog", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001561550"},
    "DE": {"name": "Deere & Company", "sector": "Industrials", "sub_industry": "Agricultural & Farm Machinery", "cik": "0000315189"},
    "DECK": {"name": "Deckers Brands", "sector": "Consumer Discretionary", "sub_industry": "Footwear", "cik": "0000910521"},
    "DELL": {"name": "Dell Technologies", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0001571996"},
    "DG": {"name": "Dollar General", "sector": "Consumer Staples", "sub_industry": "Consumer Staples Merchandise Retail", "cik": "0000029534"},
    "DGX": {"name": "Quest Diagnostics", "sector": "Health Care", "sub_industry": "Health Care Services", "cik": "0001022079"},
    "DHI": {"name": "D. R. Horton", "sector": "Consumer Discretionary", "sub_industry": "Homebuilding", "cik": "0000882184"},
    "DHR": {"name": "Danaher Corporation", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0000313616"},
    "DIS": {"name": "Walt Disney Company (The)", "sector": "Communication Services", "sub_industry": "Movies & Entertainment", "cik": "0001744489"},
    "DLR": {"name": "Digital Realty", "sector": "Real Estate", "sub_industry": "Data Center REITs", "cik": "0001297996"},
    "DLTR": {"name": "Dollar Tree", "sector": "Consumer Staples", "sub_industry": "Consumer Staples Merchandise Retail", "cik": "0000935703"},
    "DOC": {"name": "Healthpeak Properties", "sector": "Real Estate", "sub_industry": "Health Care REITs", "cik": "0000765880"},
    "DOV": {"name": "Dover Corporation", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000029905"},
    "DOW": {"name": "Dow Inc.", "sector": "Materials", "sub_industry": "Commodity Chemicals", "cik": "0001751788"},
    "DPZ": {"name": "Domino\'s", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0001286681"},
    "DRI": {"name": "Darden Restaurants", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0000940944"},
    "DTE": {"name": "DTE Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000936340"},
    "DUK": {"name": "Duke Energy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001326160"},
    "DVA": {"name": "DaVita", "sector": "Health Care", "sub_industry": "Health Care Services", "cik": "0000927066"},
    "DVN": {"name": "Devon Energy", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0001090012"},
    "DXCM": {"name": "Dexcom", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001093557"},
    "EA": {"name": "Electronic Arts", "sector": "Communication Services", "sub_industry": "Interactive Home Entertainment", "cik": "0000712515"},
    "EBAY": {"name": "eBay Inc.", "sector": "Consumer Discretionary", "sub_industry": "Broadline Retail", "cik": "0001065088"},
    "ECHO": {"name": "EchoStar", "sector": "Communication Services", "sub_industry": "Wireless Telecommunication Services", "cik": "0001415404"},
    "ECL": {"name": "Ecolab", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0000031462"},
    "ED": {"name": "Consolidated Edison", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001047862"},
    "EFX": {"name": "Equifax", "sector": "Industrials", "sub_industry": "Research & Consulting Services", "cik": "0000033185"},
    "EG": {"name": "Everest Group", "sector": "Financials", "sub_industry": "Reinsurance", "cik": "0001095073"},
    "EIX": {"name": "Edison International", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000827052"},
    "EL": {"name": "Estée Lauder Companies (The)", "sector": "Consumer Staples", "sub_industry": "Personal Care Products", "cik": "0001001250"},
    "ELV": {"name": "Elevance Health", "sector": "Health Care", "sub_industry": "Managed Health Care", "cik": "0001156039"},
    "EME": {"name": "Emcor", "sector": "Industrials", "sub_industry": "Construction & Engineering", "cik": "0000105634"},
    "EMR": {"name": "Emerson Electric", "sector": "Industrials", "sub_industry": "Electrical Components & Equipment", "cik": "0000032604"},
    "EOG": {"name": "EOG Resources", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0000821189"},
    "EQIX": {"name": "Equinix", "sector": "Real Estate", "sub_industry": "Data Center REITs", "cik": "0001101239"},
    "EQR": {"name": "Equity Residential", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000906107"},
    "EQT": {"name": "EQT Corporation", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0000033213"},
    "ERIE": {"name": "Erie Indemnity", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0000922621"},
    "ES": {"name": "Eversource Energy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000072741"},
    "ESS": {"name": "Essex Property Trust", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000920522"},
    "ETN": {"name": "Eaton Corporation", "sector": "Industrials", "sub_industry": "Electrical Components & Equipment", "cik": "0001551182"},
    "ETR": {"name": "Entergy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000065984"},
    "EVRG": {"name": "Evergy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001711269"},
    "EW": {"name": "Edwards Lifesciences", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001099800"},
    "EXC": {"name": "Exelon", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001109357"},
    "EXE": {"name": "Expand Energy", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0000895126"},
    "EXPD": {"name": "Expeditors International", "sector": "Industrials", "sub_industry": "Air Freight & Logistics", "cik": "0000746515"},
    "EXPE": {"name": "Expedia Group", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001324424"},
    "EXR": {"name": "Extra Space Storage", "sector": "Real Estate", "sub_industry": "Self-Storage REITs", "cik": "0001289490"},
    "F": {"name": "Ford Motor Company", "sector": "Consumer Discretionary", "sub_industry": "Automobile Manufacturers", "cik": "0000037996"},
    "FANG": {"name": "Diamondback Energy", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0001539838"},
    "FAST": {"name": "Fastenal", "sector": "Industrials", "sub_industry": "Trading Companies & Distributors", "cik": "0000815556"},
    "FCX": {"name": "Freeport-McMoRan", "sector": "Materials", "sub_industry": "Copper", "cik": "0000831259"},
    "FDS": {"name": "FactSet", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001013237"},
    "FDX": {"name": "FedEx", "sector": "Industrials", "sub_industry": "Air Freight & Logistics", "cik": "0001048911"},
    "FDXF": {"name": "FedEx Freight", "sector": "Industrials", "sub_industry": "Cargo Ground Transportation", "cik": "0002082247"},
    "FE": {"name": "FirstEnergy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001031296"},
    "FFIV": {"name": "F5, Inc.", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0001048695"},
    "FICO": {"name": "Fair Isaac", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000814547"},
    "FIS": {"name": "Fidelity National Information Services", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001136893"},
    "FISV": {"name": "Fiserv", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0000798354"},
    "FITB": {"name": "Fifth Third Bancorp", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0000035527"},
    "FIX": {"name": "Comfort Systems USA", "sector": "Industrials", "sub_industry": "Construction & Engineering", "cik": "0001035983"},
    "FLEX": {"name": "Flex Ltd.", "sector": "Information Technology", "sub_industry": "Electronic Manufacturing Services", "cik": "0000866374"},
    "FOX": {"name": "Fox Corporation (Class B)", "sector": "Communication Services", "sub_industry": "Broadcasting", "cik": "0001754301"},
    "FOXA": {"name": "Fox Corporation (Class A)", "sector": "Communication Services", "sub_industry": "Broadcasting", "cik": "0001754301"},
    "FRT": {"name": "Federal Realty Investment Trust", "sector": "Real Estate", "sub_industry": "Retail REITs", "cik": "0000034903"},
    "FSLR": {"name": "First Solar", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001274494"},
    "FTNT": {"name": "Fortinet", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0001262039"},
    "FTV": {"name": "Fortive", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0001659166"},
    "GD": {"name": "General Dynamics", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000040533"},
    "GDDY": {"name": "GoDaddy", "sector": "Information Technology", "sub_industry": "Internet Services & Infrastructure", "cik": "0001609711"},
    "GE": {"name": "GE Aerospace", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000040545"},
    "GEHC": {"name": "GE HealthCare", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001932393"},
    "GEN": {"name": "Gen Digital", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0000849399"},
    "GEV": {"name": "GE Vernova", "sector": "Industrials", "sub_industry": "Heavy Electrical Equipment", "cik": "0001996810"},
    "GILD": {"name": "Gilead Sciences", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000882095"},
    "GIS": {"name": "General Mills", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000040704"},
    "GL": {"name": "Globe Life", "sector": "Financials", "sub_industry": "Life & Health Insurance", "cik": "0000320335"},
    "GLW": {"name": "Corning Inc.", "sector": "Information Technology", "sub_industry": "Electronic Components", "cik": "0000024741"},
    "GM": {"name": "General Motors", "sector": "Consumer Discretionary", "sub_industry": "Automobile Manufacturers", "cik": "0001467858"},
    "GNRC": {"name": "Generac", "sector": "Industrials", "sub_industry": "Heavy Electrical Equipment", "cik": "0001474735"},
    "GOOG": {"name": "Alphabet Inc. (Class C)", "sector": "Communication Services", "sub_industry": "Interactive Media & Services", "cik": "0001652044"},
    "GOOGL": {"name": "Alphabet Inc. (Class A)", "sector": "Communication Services", "sub_industry": "Interactive Media & Services", "cik": "0001652044"},
    "GPC": {"name": "Genuine Parts Company", "sector": "Consumer Discretionary", "sub_industry": "Distributors", "cik": "0000040987"},
    "GPN": {"name": "Global Payments", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001123360"},
    "GRMN": {"name": "Garmin", "sector": "Consumer Discretionary", "sub_industry": "Consumer Electronics", "cik": "0001121788"},
    "GS": {"name": "Goldman Sachs", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0000886982"},
    "GWW": {"name": "W. W. Grainger", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000277135"},
    "HAL": {"name": "Halliburton", "sector": "Energy", "sub_industry": "Oil & Gas Equipment & Services", "cik": "0000045012"},
    "HAS": {"name": "Hasbro", "sector": "Consumer Discretionary", "sub_industry": "Leisure Products", "cik": "0000046080"},
    "HBAN": {"name": "Huntington Bancshares", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0000049196"},
    "HCA": {"name": "HCA Healthcare", "sector": "Health Care", "sub_industry": "Health Care Facilities", "cik": "0000860730"},
    "HD": {"name": "Home Depot (The)", "sector": "Consumer Discretionary", "sub_industry": "Home Improvement Retail", "cik": "0000354950"},
    "HIG": {"name": "Hartford (The)", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000874766"},
    "HII": {"name": "Huntington Ingalls Industries", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0001501585"},
    "HLT": {"name": "Hilton Worldwide", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001585689"},
    "HON": {"name": "Honeywell Technologies", "sector": "Industrials", "sub_industry": "Industrial Conglomerates", "cik": "0000773840"},
    "HONA": {"name": "Honeywell Aerospace", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0002089271"},
    "HOOD": {"name": "Robinhood Markets", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0001783879"},
    "HPE": {"name": "Hewlett Packard Enterprise", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0001645590"},
    "HPQ": {"name": "HP Inc.", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0000047217"},
    "HRL": {"name": "Hormel Foods", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000048465"},
    "HSIC": {"name": "Henry Schein", "sector": "Health Care", "sub_industry": "Health Care Distributors", "cik": "0001000228"},
    "HST": {"name": "Host Hotels & Resorts", "sector": "Real Estate", "sub_industry": "Hotel & Resort REITs", "cik": "0001070750"},
    "HSY": {"name": "Hershey Company (The)", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000047111"},
    "HUBB": {"name": "Hubbell Incorporated", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000048898"},
    "HUM": {"name": "Humana", "sector": "Health Care", "sub_industry": "Managed Health Care", "cik": "0000049071"},
    "HWM": {"name": "Howmet Aerospace", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000004281"},
    "IBKR": {"name": "Interactive Brokers", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0001381197"},
    "IBM": {"name": "IBM", "sector": "Information Technology", "sub_industry": "IT Consulting & Other Services", "cik": "0000051143"},
    "ICE": {"name": "Intercontinental Exchange", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001571949"},
    "IDXX": {"name": "Idexx Laboratories", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000874716"},
    "IEX": {"name": "IDEX Corporation", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000832101"},
    "IFF": {"name": "International Flavors & Fragrances", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0000051253"},
    "INCY": {"name": "Incyte", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000879169"},
    "INTC": {"name": "Intel", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000050863"},
    "INTU": {"name": "Intuit", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000896878"},
    "INVH": {"name": "Invitation Homes", "sector": "Real Estate", "sub_industry": "Single-Family Residential REITs", "cik": "0001687229"},
    "IP": {"name": "International Paper", "sector": "Materials", "sub_industry": "Paper & Plastic Packaging Products & Materials", "cik": "0000051434"},
    "IQV": {"name": "IQVIA", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0001478242"},
    "IR": {"name": "Ingersoll Rand", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0001699150"},
    "IRM": {"name": "Iron Mountain", "sector": "Real Estate", "sub_industry": "Other Specialized REITs", "cik": "0001020569"},
    "ISRG": {"name": "Intuitive Surgical", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001035267"},
    "IT": {"name": "Gartner", "sector": "Information Technology", "sub_industry": "IT Consulting & Other Services", "cik": "0000749251"},
    "ITW": {"name": "Illinois Tool Works", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000049826"},
    "IVZ": {"name": "Invesco", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0000914208"},
    "J": {"name": "Jacobs Solutions", "sector": "Industrials", "sub_industry": "Construction & Engineering", "cik": "0000052988"},
    "JBHT": {"name": "J.B. Hunt", "sector": "Industrials", "sub_industry": "Cargo Ground Transportation", "cik": "0000728535"},
    "JBL": {"name": "Jabil", "sector": "Information Technology", "sub_industry": "Electronic Manufacturing Services", "cik": "0000898293"},
    "JCI": {"name": "Johnson Controls", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0000833444"},
    "JKHY": {"name": "Jack Henry & Associates", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0000779152"},
    "JNJ": {"name": "Johnson & Johnson", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0000200406"},
    "JPM": {"name": "JPMorgan Chase", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000019617"},
    "KDP": {"name": "Keurig Dr Pepper", "sector": "Consumer Staples", "sub_industry": "Soft Drinks & Non-alcoholic Beverages", "cik": "0001418135"},
    "KEY": {"name": "KeyCorp", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0000091576"},
    "KEYS": {"name": "Keysight Technologies", "sector": "Information Technology", "sub_industry": "Electronic Equipment & Instruments", "cik": "0001601046"},
    "KHC": {"name": "Kraft Heinz", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0001637459"},
    "KIM": {"name": "Kimco Realty", "sector": "Real Estate", "sub_industry": "Retail REITs", "cik": "0000879101"},
    "KKR": {"name": "KKR & Co.", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001404912"},
    "KLAC": {"name": "KLA Corporation", "sector": "Information Technology", "sub_industry": "Semiconductor Materials & Equipment", "cik": "0000319201"},
    "KMB": {"name": "Kimberly-Clark", "sector": "Consumer Staples", "sub_industry": "Household Products", "cik": "0000055785"},
    "KMI": {"name": "Kinder Morgan", "sector": "Energy", "sub_industry": "Oil & Gas Storage & Transportation", "cik": "0001506307"},
    "KO": {"name": "Coca-Cola Company (The)", "sector": "Consumer Staples", "sub_industry": "Soft Drinks & Non-alcoholic Beverages", "cik": "0000021344"},
    "KR": {"name": "Kroger", "sector": "Consumer Staples", "sub_industry": "Food Retail", "cik": "0000056873"},
    "KVUE": {"name": "Kenvue", "sector": "Consumer Staples", "sub_industry": "Personal Care Products", "cik": "0001944048"},
    "L": {"name": "Loews Corporation", "sector": "Financials", "sub_industry": "Multi-line Insurance", "cik": "0000060086"},
    "LDOS": {"name": "Leidos", "sector": "Industrials", "sub_industry": "Diversified Support Services", "cik": "0001336920"},
    "LEN": {"name": "Lennar", "sector": "Consumer Discretionary", "sub_industry": "Homebuilding", "cik": "0000920760"},
    "LH": {"name": "Labcorp", "sector": "Health Care", "sub_industry": "Health Care Services", "cik": "0000920148"},
    "LHX": {"name": "L3Harris", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000202058"},
    "LII": {"name": "Lennox International", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0001069202"},
    "LIN": {"name": "Linde plc", "sector": "Materials", "sub_industry": "Industrial Gases", "cik": "0001707925"},
    "LITE": {"name": "Lumentum", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0001633978"},
    "LLY": {"name": "Lilly (Eli)", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0000059478"},
    "LMT": {"name": "Lockheed Martin", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000936468"},
    "LNT": {"name": "Alliant Energy", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000352541"},
    "LOW": {"name": "Lowe\'s", "sector": "Consumer Discretionary", "sub_industry": "Home Improvement Retail", "cik": "0000060667"},
    "LRCX": {"name": "Lam Research", "sector": "Information Technology", "sub_industry": "Semiconductor Materials & Equipment", "cik": "0000707549"},
    "LULU": {"name": "Lululemon Athletica", "sector": "Consumer Discretionary", "sub_industry": "Apparel, Accessories & Luxury Goods", "cik": "0001397187"},
    "LUV": {"name": "Southwest Airlines", "sector": "Industrials", "sub_industry": "Passenger Airlines", "cik": "0000092380"},
    "LVS": {"name": "Las Vegas Sands", "sector": "Consumer Discretionary", "sub_industry": "Casinos & Gaming", "cik": "0001300514"},
    "LYB": {"name": "LyondellBasell", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0001489393"},
    "LYV": {"name": "Live Nation Entertainment", "sector": "Communication Services", "sub_industry": "Movies & Entertainment", "cik": "0001335258"},
    "MA": {"name": "Mastercard", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001141391"},
    "MAA": {"name": "Mid-America Apartment Communities", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000912595"},
    "MAR": {"name": "Marriott International", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001048286"},
    "MAS": {"name": "Masco", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0000062996"},
    "MCD": {"name": "McDonald\'s", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0000063908"},
    "MCHP": {"name": "Microchip Technology", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000827054"},
    "MCK": {"name": "McKesson Corporation", "sector": "Health Care", "sub_industry": "Health Care Distributors", "cik": "0000927653"},
    "MCO": {"name": "Moody\'s Corporation", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001059556"},
    "MDLZ": {"name": "Mondelez International", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0001103982"},
    "MDT": {"name": "Medtronic", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001613103"},
    "MET": {"name": "MetLife", "sector": "Financials", "sub_industry": "Life & Health Insurance", "cik": "0001099219"},
    "META": {"name": "Meta Platforms", "sector": "Communication Services", "sub_industry": "Interactive Media & Services", "cik": "0001326801"},
    "MGM": {"name": "MGM Resorts", "sector": "Consumer Discretionary", "sub_industry": "Casinos & Gaming", "cik": "0000789570"},
    "MKC": {"name": "McCormick & Company", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000063754"},
    "MLM": {"name": "Martin Marietta Materials", "sector": "Materials", "sub_industry": "Construction Materials", "cik": "0000916076"},
    "MMM": {"name": "3M", "sector": "Industrials", "sub_industry": "Industrial Conglomerates", "cik": "0000066740"},
    "MNST": {"name": "Monster Beverage", "sector": "Consumer Staples", "sub_industry": "Soft Drinks & Non-alcoholic Beverages", "cik": "0000865752"},
    "MO": {"name": "Altria", "sector": "Consumer Staples", "sub_industry": "Tobacco", "cik": "0000764180"},
    "MOS": {"name": "Mosaic Company (The)", "sector": "Materials", "sub_industry": "Fertilizers & Agricultural Chemicals", "cik": "0001285785"},
    "MPC": {"name": "Marathon Petroleum", "sector": "Energy", "sub_industry": "Oil & Gas Refining & Marketing", "cik": "0001510295"},
    "MPWR": {"name": "Monolithic Power Systems", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001280452"},
    "MRK": {"name": "Merck & Co.", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0000310158"},
    "MRNA": {"name": "Moderna", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0001682852"},
    "MRSH": {"name": "Marsh McLennan", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0000062709"},
    "MRVL": {"name": "Marvell Technology", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001835632"},
    "MS": {"name": "Morgan Stanley", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0000895421"},
    "MSCI": {"name": "MSCI Inc.", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001408198"},
    "MSFT": {"name": "Microsoft", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0000789019"},
    "MSI": {"name": "Motorola Solutions", "sector": "Information Technology", "sub_industry": "Communications Equipment", "cik": "0000068505"},
    "MTB": {"name": "M&T Bank", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0000036270"},
    "MTD": {"name": "Mettler Toledo", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0001037646"},
    "MU": {"name": "Micron Technology", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000723125"},
    "NCLH": {"name": "Norwegian Cruise Line Holdings", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0001513761"},
    "NDAQ": {"name": "Nasdaq, Inc.", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0001120193"},
    "NDSN": {"name": "Nordson Corporation", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000072331"},
    "NEE": {"name": "NextEra Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000753308"},
    "NEM": {"name": "Newmont", "sector": "Materials", "sub_industry": "Gold", "cik": "0001164727"},
    "NFLX": {"name": "Netflix", "sector": "Communication Services", "sub_industry": "Movies & Entertainment", "cik": "0001065280"},
    "NI": {"name": "NiSource", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001111711"},
    "NKE": {"name": "Nike, Inc.", "sector": "Consumer Discretionary", "sub_industry": "Apparel, Accessories & Luxury Goods", "cik": "0000320187"},
    "NOC": {"name": "Northrop Grumman", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0001133421"},
    "NOW": {"name": "ServiceNow", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0001373715"},
    "NRG": {"name": "NRG Energy", "sector": "Utilities", "sub_industry": "Independent Power Producers & Energy Traders", "cik": "0001013871"},
    "NSC": {"name": "Norfolk Southern", "sector": "Industrials", "sub_industry": "Rail Transportation", "cik": "0000702165"},
    "NTAP": {"name": "NetApp", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0001002047"},
    "NTRS": {"name": "Northern Trust", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0000073124"},
    "NUE": {"name": "Nucor", "sector": "Materials", "sub_industry": "Steel", "cik": "0000073309"},
    "NVDA": {"name": "Nvidia", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001045810"},
    "NVR": {"name": "NVR, Inc.", "sector": "Consumer Discretionary", "sub_industry": "Homebuilding", "cik": "0000906163"},
    "NWS": {"name": "News Corp (Class B)", "sector": "Communication Services", "sub_industry": "Publishing", "cik": "0001564708"},
    "NWSA": {"name": "News Corp (Class A)", "sector": "Communication Services", "sub_industry": "Publishing", "cik": "0001564708"},
    "NXPI": {"name": "NXP Semiconductors", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001413447"},
    "O": {"name": "Realty Income", "sector": "Real Estate", "sub_industry": "Retail REITs", "cik": "0000726728"},
    "ODFL": {"name": "Old Dominion", "sector": "Industrials", "sub_industry": "Cargo Ground Transportation", "cik": "0000878927"},
    "OKE": {"name": "Oneok", "sector": "Energy", "sub_industry": "Oil & Gas Storage & Transportation", "cik": "0001039684"},
    "OMC": {"name": "Omnicom Group", "sector": "Communication Services", "sub_industry": "Advertising", "cik": "0000029989"},
    "ON": {"name": "ON Semiconductor", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0001097864"},
    "ORCL": {"name": "Oracle Corporation", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001341439"},
    "ORLY": {"name": "O’Reilly Automotive", "sector": "Consumer Discretionary", "sub_industry": "Automotive Retail", "cik": "0000898173"},
    "OTIS": {"name": "Otis Worldwide", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0001781335"},
    "OXY": {"name": "Occidental Petroleum", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0000797468"},
    "PANW": {"name": "Palo Alto Networks", "sector": "Information Technology", "sub_industry": "Systems Software", "cik": "0001327567"},
    "PAYX": {"name": "Paychex", "sector": "Industrials", "sub_industry": "Human Resource & Employment Services", "cik": "0000723531"},
    "PCAR": {"name": "Paccar", "sector": "Industrials", "sub_industry": "Construction Machinery & Heavy Transportation Equipment", "cik": "0000075362"},
    "PCG": {"name": "PG&E Corporation", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001004980"},
    "PEG": {"name": "Public Service Enterprise Group", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000788784"},
    "PEP": {"name": "PepsiCo", "sector": "Consumer Staples", "sub_industry": "Soft Drinks & Non-alcoholic Beverages", "cik": "0000077476"},
    "PFE": {"name": "Pfizer", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0000078003"},
    "PFG": {"name": "Principal Financial Group", "sector": "Financials", "sub_industry": "Life & Health Insurance", "cik": "0001126328"},
    "PG": {"name": "Procter & Gamble", "sector": "Consumer Staples", "sub_industry": "Personal Care Products", "cik": "0000080424"},
    "PGR": {"name": "Progressive Corporation", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000080661"},
    "PH": {"name": "Parker Hannifin", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000076334"},
    "PHM": {"name": "PulteGroup", "sector": "Consumer Discretionary", "sub_industry": "Homebuilding", "cik": "0000822416"},
    "PKG": {"name": "Packaging Corporation of America", "sector": "Materials", "sub_industry": "Paper & Plastic Packaging Products & Materials", "cik": "0000075677"},
    "PLD": {"name": "Prologis", "sector": "Real Estate", "sub_industry": "Industrial REITs", "cik": "0001045609"},
    "PLTR": {"name": "Palantir Technologies", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001321655"},
    "PM": {"name": "Philip Morris International", "sector": "Consumer Staples", "sub_industry": "Tobacco", "cik": "0001413329"},
    "PNC": {"name": "PNC Financial Services", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000713676"},
    "PNR": {"name": "Pentair", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000077360"},
    "PNW": {"name": "Pinnacle West Capital", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000764622"},
    "PODD": {"name": "Insulet Corporation", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001145197"},
    "PPG": {"name": "PPG Industries", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0000079879"},
    "PPL": {"name": "PPL Corporation", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000922224"},
    "PRU": {"name": "Prudential Financial", "sector": "Financials", "sub_industry": "Life & Health Insurance", "cik": "0001137774"},
    "PSA": {"name": "Public Storage", "sector": "Real Estate", "sub_industry": "Self-Storage REITs", "cik": "0001393311"},
    "PSKY": {"name": "Paramount Skydance Corporation", "sector": "Communication Services", "sub_industry": "Movies & Entertainment", "cik": "0002041610"},
    "PSX": {"name": "Phillips 66", "sector": "Energy", "sub_industry": "Oil & Gas Refining & Marketing", "cik": "0001534701"},
    "PTC": {"name": "PTC Inc.", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000857005"},
    "PWR": {"name": "Quanta Services", "sector": "Industrials", "sub_industry": "Construction & Engineering", "cik": "0001050915"},
    "PYPL": {"name": "PayPal", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001633917"},
    "Q": {"name": "Qnity Electronics", "sector": "Information Technology", "sub_industry": "Semiconductor Materials & Equipment", "cik": "0002058873"},
    "QCOM": {"name": "Qualcomm", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000804328"},
    "RCL": {"name": "Royal Caribbean Group", "sector": "Consumer Discretionary", "sub_industry": "Hotels, Resorts & Cruise Lines", "cik": "0000884887"},
    "REG": {"name": "Regency Centers", "sector": "Real Estate", "sub_industry": "Retail REITs", "cik": "0000910606"},
    "REGN": {"name": "Regeneron Pharmaceuticals", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000872589"},
    "RF": {"name": "Regions Financial Corporation", "sector": "Financials", "sub_industry": "Regional Banks", "cik": "0001281761"},
    "RJF": {"name": "Raymond James Financial", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0000720005"},
    "RL": {"name": "Ralph Lauren Corporation", "sector": "Consumer Discretionary", "sub_industry": "Apparel, Accessories & Luxury Goods", "cik": "0001037038"},
    "RMD": {"name": "ResMed", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000943819"},
    "ROK": {"name": "Rockwell Automation", "sector": "Industrials", "sub_industry": "Electrical Components & Equipment", "cik": "0001024478"},
    "ROL": {"name": "Rollins, Inc.", "sector": "Industrials", "sub_industry": "Environmental & Facilities Services", "cik": "0000084839"},
    "ROP": {"name": "Roper Technologies", "sector": "Information Technology", "sub_industry": "Electronic Equipment & Instruments", "cik": "0000882835"},
    "ROST": {"name": "Ross Stores", "sector": "Consumer Discretionary", "sub_industry": "Apparel Retail", "cik": "0000745732"},
    "RSG": {"name": "Republic Services", "sector": "Industrials", "sub_industry": "Environmental & Facilities Services", "cik": "0001060391"},
    "RTX": {"name": "RTX Corporation", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000101829"},
    "RVTY": {"name": "Revvity", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000031791"},
    "SBAC": {"name": "SBA Communications", "sector": "Real Estate", "sub_industry": "Telecom Tower REITs", "cik": "0001034054"},
    "SBUX": {"name": "Starbucks", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0000829224"},
    "SCHW": {"name": "Charles Schwab Corporation", "sector": "Financials", "sub_industry": "Investment Banking & Brokerage", "cik": "0000316709"},
    "SHW": {"name": "Sherwin-Williams", "sector": "Materials", "sub_industry": "Specialty Chemicals", "cik": "0000089800"},
    "SJM": {"name": "J.M. Smucker Company (The)", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000091419"},
    "SLB": {"name": "Schlumberger", "sector": "Energy", "sub_industry": "Oil & Gas Equipment & Services", "cik": "0000087347"},
    "SMCI": {"name": "Supermicro", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0001375365"},
    "SNA": {"name": "Snap-on", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000091440"},
    "SNDK": {"name": "Sandisk", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0002023554"},
    "SNPS": {"name": "Synopsys", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000883241"},
    "SO": {"name": "Southern Company", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000092122"},
    "SOLV": {"name": "Solventum", "sector": "Health Care", "sub_industry": "Health Care Technology", "cik": "0001964738"},
    "SPG": {"name": "Simon Property Group", "sector": "Real Estate", "sub_industry": "Retail REITs", "cik": "0001063761"},
    "SPGI": {"name": "S&P Global", "sector": "Financials", "sub_industry": "Financial Exchanges & Data", "cik": "0000064040"},
    "SRE": {"name": "Sempra", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0001032208"},
    "STE": {"name": "Steris", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001757898"},
    "STLD": {"name": "Steel Dynamics", "sector": "Materials", "sub_industry": "Steel", "cik": "0001022671"},
    "STT": {"name": "State Street Corporation", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0000093751"},
    "STX": {"name": "Seagate Technology", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0001137789"},
    "STZ": {"name": "Constellation Brands", "sector": "Consumer Staples", "sub_industry": "Distillers & Vintners", "cik": "0000016918"},
    "SW": {"name": "Smurfit Westrock", "sector": "Materials", "sub_industry": "Paper & Plastic Packaging Products & Materials", "cik": "0002005951"},
    "SWK": {"name": "Stanley Black & Decker", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0000093556"},
    "SWKS": {"name": "Skyworks Solutions", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000004127"},
    "SYF": {"name": "Synchrony Financial", "sector": "Financials", "sub_industry": "Consumer Finance", "cik": "0001601712"},
    "SYK": {"name": "Stryker Corporation", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0000310764"},
    "SYY": {"name": "Sysco", "sector": "Consumer Staples", "sub_industry": "Food Distributors", "cik": "0000096021"},
    "T": {"name": "AT&T", "sector": "Communication Services", "sub_industry": "Integrated Telecommunication Services", "cik": "0000732717"},
    "TAP": {"name": "Molson Coors Beverage Company", "sector": "Consumer Staples", "sub_industry": "Brewers", "cik": "0000024545"},
    "TDG": {"name": "TransDigm Group", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0001260221"},
    "TDY": {"name": "Teledyne Technologies", "sector": "Information Technology", "sub_industry": "Electronic Equipment & Instruments", "cik": "0001094285"},
    "TECH": {"name": "Bio-Techne", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0000842023"},
    "TEL": {"name": "TE Connectivity", "sector": "Information Technology", "sub_industry": "Electronic Manufacturing Services", "cik": "0001385157"},
    "TER": {"name": "Teradyne", "sector": "Information Technology", "sub_industry": "Semiconductor Materials & Equipment", "cik": "0000097210"},
    "TFC": {"name": "Truist Financial", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000092230"},
    "TGT": {"name": "Target Corporation", "sector": "Consumer Staples", "sub_industry": "Consumer Staples Merchandise Retail", "cik": "0000027419"},
    "TJX": {"name": "TJX Companies", "sector": "Consumer Discretionary", "sub_industry": "Apparel Retail", "cik": "0000109198"},
    "TKO": {"name": "TKO Group Holdings", "sector": "Communication Services", "sub_industry": "Movies & Entertainment", "cik": "0001973266"},
    "TMO": {"name": "Thermo Fisher Scientific", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0000097745"},
    "TMUS": {"name": "T-Mobile US", "sector": "Communication Services", "sub_industry": "Wireless Telecommunication Services", "cik": "0001283699"},
    "TPL": {"name": "Texas Pacific Land Corporation", "sector": "Energy", "sub_industry": "Oil & Gas Exploration & Production", "cik": "0001811074"},
    "TPR": {"name": "Tapestry, Inc.", "sector": "Consumer Discretionary", "sub_industry": "Apparel, Accessories & Luxury Goods", "cik": "0001116132"},
    "TRGP": {"name": "Targa Resources", "sector": "Energy", "sub_industry": "Oil & Gas Storage & Transportation", "cik": "0001389170"},
    "TRMB": {"name": "Trimble Inc.", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000864749"},
    "TROW": {"name": "T. Rowe Price", "sector": "Financials", "sub_industry": "Asset Management & Custody Banks", "cik": "0001113169"},
    "TRV": {"name": "Travelers Companies (The)", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000086312"},
    "TSCO": {"name": "Tractor Supply", "sector": "Consumer Discretionary", "sub_industry": "Other Specialty Retail", "cik": "0000916365"},
    "TSLA": {"name": "Tesla, Inc.", "sector": "Consumer Discretionary", "sub_industry": "Automobile Manufacturers", "cik": "0001318605"},
    "TSN": {"name": "Tyson Foods", "sector": "Consumer Staples", "sub_industry": "Packaged Foods & Meats", "cik": "0000100493"},
    "TT": {"name": "Trane Technologies", "sector": "Industrials", "sub_industry": "Building Products", "cik": "0001466258"},
    "TTD": {"name": "Trade Desk (The)", "sector": "Communication Services", "sub_industry": "Advertising", "cik": "0001671933"},
    "TTWO": {"name": "Take-Two Interactive", "sector": "Communication Services", "sub_industry": "Interactive Home Entertainment", "cik": "0000946581"},
    "TXN": {"name": "Texas Instruments", "sector": "Information Technology", "sub_industry": "Semiconductors", "cik": "0000097476"},
    "TXT": {"name": "Textron", "sector": "Industrials", "sub_industry": "Aerospace & Defense", "cik": "0000217346"},
    "TYL": {"name": "Tyler Technologies", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0000860731"},
    "UAL": {"name": "United Airlines Holdings", "sector": "Industrials", "sub_industry": "Passenger Airlines", "cik": "0000100517"},
    "UBER": {"name": "Uber", "sector": "Industrials", "sub_industry": "Passenger Ground Transportation", "cik": "0001543151"},
    "UDR": {"name": "UDR, Inc.", "sector": "Real Estate", "sub_industry": "Multi-Family Residential REITs", "cik": "0000074208"},
    "UHS": {"name": "Universal Health Services", "sector": "Health Care", "sub_industry": "Health Care Facilities", "cik": "0000352915"},
    "ULTA": {"name": "Ulta Beauty", "sector": "Consumer Discretionary", "sub_industry": "Other Specialty Retail", "cik": "0001403568"},
    "UNH": {"name": "UnitedHealth Group", "sector": "Health Care", "sub_industry": "Managed Health Care", "cik": "0000731766"},
    "UNP": {"name": "Union Pacific Corporation", "sector": "Industrials", "sub_industry": "Rail Transportation", "cik": "0000100885"},
    "UPS": {"name": "United Parcel Service", "sector": "Industrials", "sub_industry": "Air Freight & Logistics", "cik": "0001090727"},
    "URI": {"name": "United Rentals", "sector": "Industrials", "sub_industry": "Trading Companies & Distributors", "cik": "0001067701"},
    "USB": {"name": "U.S. Bancorp", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000036104"},
    "V": {"name": "Visa Inc.", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001403161"},
    "VEEV": {"name": "Veeva Systems", "sector": "Health Care", "sub_industry": "Health Care Technology", "cik": "0001393052"},
    "VICI": {"name": "Vici Properties", "sector": "Real Estate", "sub_industry": "Hotel & Resort REITs", "cik": "0001705696"},
    "VLO": {"name": "Valero Energy", "sector": "Energy", "sub_industry": "Oil & Gas Refining & Marketing", "cik": "0001035002"},
    "VLTO": {"name": "Veralto", "sector": "Industrials", "sub_industry": "Environmental & Facilities Services", "cik": "0001967680"},
    "VMC": {"name": "Vulcan Materials Company", "sector": "Materials", "sub_industry": "Construction Materials", "cik": "0001396009"},
    "VRSK": {"name": "Verisk Analytics", "sector": "Industrials", "sub_industry": "Research & Consulting Services", "cik": "0001442145"},
    "VRSN": {"name": "Verisign", "sector": "Information Technology", "sub_industry": "Internet Services & Infrastructure", "cik": "0001014473"},
    "VRT": {"name": "Vertiv", "sector": "Industrials", "sub_industry": "Electrical Components & Equipment", "cik": "0001674101"},
    "VRTX": {"name": "Vertex Pharmaceuticals", "sector": "Health Care", "sub_industry": "Biotechnology", "cik": "0000875320"},
    "VST": {"name": "Vistra Corp.", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0001692819"},
    "VTR": {"name": "Ventas", "sector": "Real Estate", "sub_industry": "Health Care REITs", "cik": "0000740260"},
    "VTRS": {"name": "Viatris", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0001792044"},
    "VZ": {"name": "Verizon", "sector": "Communication Services", "sub_industry": "Integrated Telecommunication Services", "cik": "0000732712"},
    "WAB": {"name": "Wabtec", "sector": "Industrials", "sub_industry": "Construction Machinery & Heavy Transportation Equipment", "cik": "0000943452"},
    "WAT": {"name": "Waters Corporation", "sector": "Health Care", "sub_industry": "Life Sciences Tools & Services", "cik": "0001000697"},
    "WBD": {"name": "Warner Bros. Discovery", "sector": "Communication Services", "sub_industry": "Broadcasting", "cik": "0001437107"},
    "WDAY": {"name": "Workday, Inc.", "sector": "Information Technology", "sub_industry": "Application Software", "cik": "0001327811"},
    "WDC": {"name": "Western Digital", "sector": "Information Technology", "sub_industry": "Technology Hardware, Storage & Peripherals", "cik": "0000106040"},
    "WEC": {"name": "WEC Energy Group", "sector": "Utilities", "sub_industry": "Electric Utilities", "cik": "0000783325"},
    "WELL": {"name": "Welltower", "sector": "Real Estate", "sub_industry": "Health Care REITs", "cik": "0000766704"},
    "WFC": {"name": "Wells Fargo", "sector": "Financials", "sub_industry": "Diversified Banks", "cik": "0000072971"},
    "WM": {"name": "Waste Management", "sector": "Industrials", "sub_industry": "Environmental & Facilities Services", "cik": "0000823768"},
    "WMB": {"name": "Williams Companies", "sector": "Energy", "sub_industry": "Oil & Gas Storage & Transportation", "cik": "0000107263"},
    "WMT": {"name": "Walmart", "sector": "Consumer Staples", "sub_industry": "Consumer Staples Merchandise Retail", "cik": "0000104169"},
    "WRB": {"name": "W. R. Berkley Corporation", "sector": "Financials", "sub_industry": "Property & Casualty Insurance", "cik": "0000011544"},
    "WSM": {"name": "Williams-Sonoma, Inc.", "sector": "Consumer Discretionary", "sub_industry": "Homefurnishing Retail", "cik": "0000719955"},
    "WST": {"name": "West Pharmaceutical Services", "sector": "Health Care", "sub_industry": "Health Care Supplies", "cik": "0000105770"},
    "WTW": {"name": "Willis Towers Watson", "sector": "Financials", "sub_industry": "Insurance Brokers", "cik": "0001140536"},
    "WY": {"name": "Weyerhaeuser", "sector": "Real Estate", "sub_industry": "Timber REITs", "cik": "0000106535"},
    "WYNN": {"name": "Wynn Resorts", "sector": "Consumer Discretionary", "sub_industry": "Casinos & Gaming", "cik": "0001174922"},
    "XEL": {"name": "Xcel Energy", "sector": "Utilities", "sub_industry": "Multi-Utilities", "cik": "0000072903"},
    "XOM": {"name": "ExxonMobil", "sector": "Energy", "sub_industry": "Integrated Oil & Gas", "cik": "0000034088"},
    "XYL": {"name": "Xylem Inc.", "sector": "Industrials", "sub_industry": "Industrial Machinery & Supplies & Components", "cik": "0001524472"},
    "XYZ": {"name": "Block, Inc.", "sector": "Financials", "sub_industry": "Transaction & Payment Processing Services", "cik": "0001512673"},
    "YUM": {"name": "Yum! Brands", "sector": "Consumer Discretionary", "sub_industry": "Restaurants", "cik": "0001041061"},
    "ZBH": {"name": "Zimmer Biomet", "sector": "Health Care", "sub_industry": "Health Care Equipment", "cik": "0001136869"},
    "ZBRA": {"name": "Zebra Technologies", "sector": "Information Technology", "sub_industry": "Electronic Equipment & Instruments", "cik": "0000877212"},
    "ZTS": {"name": "Zoetis", "sector": "Health Care", "sub_industry": "Pharmaceuticals", "cik": "0001555280"},
}


def get_full_universe():
    """Return deduplicated list of all tickers across S&P 500 and Nasdaq-100."""
    return sorted(set(SP500_TICKERS + NASDAQ100_TICKERS))


def get_ticker_universe_map():
    """Return dict mapping ticker -> {in_sp500, in_nasdaq100}."""
    sp500_set  = set(SP500_TICKERS)
    nasdaq_set = set(NASDAQ100_TICKERS)
    all_tickers = sp500_set | nasdaq_set
    return {
        t: {"in_sp500": t in sp500_set, "in_nasdaq100": t in nasdaq_set}
        for t in all_tickers
    }


def get_sp500_sector(ticker: str):
    """Return GICS sector for an S&P 500 ticker, or None if not found."""
    m = SP500_METADATA.get(ticker, {})
    return m.get("sector") or None


def get_sp500_metadata(ticker: str):
    """Return full metadata dict for an S&P 500 ticker, or empty dict."""
    return SP500_METADATA.get(ticker, {})
